spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: ms-config-eureka
  
eureka:
  instance:
    hostname: 192.168.129.132
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6001/eureka/

  # 禁用自我保护机制（默认开启状态）
  server:
    enable-self-preservation: false 

---
server:
  port: 6001
spring:
  profiles: prod
  application:
    name: ms-config-eureka
  
eureka:
  instance:
    hostname: 192.168.129.132
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:6001/eureka/

  # 禁用自我保护机制（默认开启状态）
  server:
    enable-self-preservation: true
#保存时注意，选择 UTF-8 保存
